# Why pandas 

pandas provides a simple to use but very capable set of functions you can use to on your data. It's integrated with many other data sceince and machine learning. 

One way you'll come across is using pandas to transform your data in a way which makes it usable with machine learning algorithms 

# What does this notebook cover?
Because the pandas library is vast, there's often many ways to do the same thing. This notebook covers some of the most fundaental function of the library, which are more than enough to get started

In [48]:
# 0. Improting pandas
"""
To get started using pandas, the first step is to improt it 

"""
import pandas as pd

print(f"pandas version:  {pd.__version__}")

pandas version:  3.0.3

In [49]:
""" 
1. Datatypes 
padas has two main datatypes, series and dataFrame.
pandas.Series -a 1 -dimesional column of data .

pandas.DataFrame(most common) - a 2-dimensional table of data with rows and columns
"""

#Creating a series of car types

car = pd.Series(["BMW", "Toyota","Honda"])

car

0       BMW
1    Toyota
2     Honda
dtype: str

In [50]:
colour = pd.Series(["Blue", "Red", "Green"])
colour

0     Blue
1      Red
2    Green
dtype: str

In [51]:
"""  
You can create a dataframe by using pd.DataFrame() and passing it a python dictionarry


"""

car_data = pd.DataFrame({"Car" : car, "Colour" : colour})
car_data

      Car Colour
0     BMW   Blue
1  Toyota    Red
2   Honda  Green

In [52]:
"""Excercises
Make a Series of different foods.
Make a Series of different dollar values (these can be integers).
Combine your Series's of foods and dollar values into a DataFrame.
"""
foods = pd.Series(["FuFu", "Fries", "Chicken"])
prices = pd.Series([4.5, 3.50, 19.20])


food =pd.DataFrame({"foods" : foods, "prices" : prices})

In [53]:
#expor ti ng
car.to_csv("exported-car-sales.xlsx",index= False)

# Describing data

One of the first things you'll want to do after import some data into pandans DataFrame is to start exploring it.

pandas has many built it functions which allow you to quickly get information about DataFrame.

let's explore some using the car_sales DataFrame .

In [54]:
"""

dtypes shows us the datatype each collumns contains
"""

car_data.dtypes

Car       str
Colour    str
dtype: object

In [55]:
"""
gives a quick statistical overview of the numerical columns

"""
car_data.describe()

        Car Colour
count     3      3
unique    3      3
top     BMW   Blue
freq      1      1

In [56]:
"""
info() shows a handful of useful information about DataFrame such as

How any entries rows there are 

How many entries (rows) there are
Whether there are missing values (if a columns non-null value is less than the number of entries, it has missing values)
       
The datatypes of each column 
"""
car_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Car     3 non-null      str
 1   Colour  3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [57]:
"""
you can also perform various stastical and mathematical methods such as .mean()
.sum()
"""

#Calling .mean() on DataFrame
print(car_data.mean(numeric_only=True))

#Calling .mean()on a series

car_prices = pd.Series([200,100,121])
print(car_prices.mean())

# Calling sum on dataFrame with nmericonly false default
print(car_data.sum(numeric_only=True))

Series([], dtype: float64)
140.33333333333334
Series([], dtype: float64)

In [58]:
#allows to view the first 5 rows of car_alwa defualt if put  umber head(7) 7 first rows
car_data.head()

      Car Colour
0     BMW   Blue
1  Toyota    Red
2   Honda  Green

In [59]:
car_data.tail(7) # same logic as head.

      Car Colour
0     BMW   Blue
1  Toyota    Red
2   Honda  Green

In [60]:
"""
youn can use .loc[] and iloc[] to select data from series and dataframes
"""

animals = pd.Series(["cat","dog","bird","fish"], index=[0,3,8,67])
animals

0      cat
3      dog
8     bird
67    fish
dtype: str

In [61]:
"""
.loc[] tqakes an integer or ;abe; as input and it chooses from series or dataframe whicheve index matches the number.
so yes the rows indexes are just numbers not necesarly in the order they appear
"""

animals.loc[3]

'dog'

In [62]:
food.loc[1]

foods     Fries
prices      3.5
Name: 1, dtype: object

In [63]:
food.iloc[1]# select exactl y at pos tion 1 even if the index was set to 67

foods     Fries
prices      3.5
Name: 1, dtype: object

In [66]:
food.loc[:,"prices"]# get all rows of the prices columns or
food["prices"]

0     4.5
1     3.5
2    19.2
Name: prices, dtype: float64

In [67]:
 #booleans also work
food[food["prices"] > 3.5]

     foods  prices
0     FuFu     4.5
2  Chicken    19.2

In [68]:
# Group by the Make column and find the mean of the other columns 
food.groupby(["prices"]).mean(numeric_only=True)

Empty DataFrame
Columns: []
Index: [3.5, 4.5, 19.2]